library(leaflet)
library(shiny)
library(tidyverse)
library(XML)
library(stringi)
library(dplyr)
library(countrycode)
library(maptools)
library(maps)
library(rworldmap)
library(shiny)
library(shinythemes)
library(sentimentr)
library(Rcpp)
library(microbenchmark)
library(rstudioapi)    
library(svMisc)

options(stringsAsFactors = FALSE)
